### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by simonprickett** [redis/redis-om-python#104]
This will be re-licensed to use the MIT license from the next release.

**Comment by gam-phon** [comment]
When will be approximately the next release? What is the roadmap for this library? python version is not active as others

**Comment by simonprickett** [comment]
@gam-phon it's likely the next release will be to swap the license to align with other Redis clients that we produce, and to do minor dependency updates.  The next features should be RediSearch aggregation and geo searching.  You're right that we're slower developing for Python than the other languages - we're currently hiring a Python Developer Relations person to help here, if you know anyone (applicants don't have to be based in the USA): https://redis.com/company/careers/jobs/developer-advocate-python/
