### ISSUE TITLE
JsonModel: find not working with bool

### ISSUE THREAD

**Issue by gam-phon** [redis/redis-om-python#109]
hello,

It does not work with bool type

**Comment by LeMoussel** [comment]
It's indicated in the documentation [Indexing JSON](https://oss.redis.com/redisearch/Indexing_JSON/#index_json_strings_and_numbers_as_text_and_numeric)
```
 Index JSON strings and numbers as TEXT and NUMERIC

    You can only index JSON strings as TEXT, TAG, or GEO (using the right syntax).
    You can only index JSON numbers as NUMERIC.
    Boolean and NULL values are ignored.
```

**Comment by simonprickett** [comment]
Closing this issue - we will look at boolean support in #193
