### ISSUE TITLE
no such index

### ISSUE THREAD

**Issue by Nishikoh** [redis/redis-om-python#111]
Set a `db` number other than 0, I got an error.
```python
import datetime
from typing import Optional

from redis_om import Field, JsonModel, Migrator, get_redis_connection


class Customer(JsonModel):
    first_name: str
    last_name: str = Field(index=True)
    email: str
    join_date: datetime.date
    age: int = Field(index=True)
    bio: Optional[str]

    class Meta:
        database = get_redis_connection(host="redis", port=6379, db=1)


andrew = Customer(
    first_name="Andrew",
    last_name="Brookins",
    email="andrew.brookins@example.com",
    join_date=datetime.date.today(),
    age=38,
)
andrew.save()
Migrator().run()

# Find all customers with the last name "Brookins"
result = Customer.find(Customer.last_name == "Brookins").all()
```
error
```py
Traceback (most recent call last):
  File "/app/aaa.py", line 30, in <module>
    Customer.find(Customer.last_name == "Brookins").all()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/redis_om/model/model.py", line 761, in all
    return self.execute()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/redis_om/model/model.py", line 725, in execute
    raw_result = self.model.db().execute_command(*args)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/redis/client.py", line 1173, in execute_command
    return conn.retry.call_with_retry(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/redis/retry.py", line 41, in call_with_retry
    return do()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/redis/client.py", line 1174, in <lambda>
    lambda: self._send_command_parse_response(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/redis/client.py", line 1150, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/redis/client.py", line 1189, in parse_response
    response = connection.read_response()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/redis/connection.py", line 817, in read_response
    raise response
redis.exceptions.ResponseError: :__main__.Customer:index: no such index
```

db number set 0 then, no error
```diff
    class Meta:
-        database = get_redis_connection(host="redis", port=6379, db=1)
+        database = get_redis_connection(host="redis", port=6379, db=0)
```
result
```sh
[Customer(pk='01FTBDC0A8D47YQ516GQ84A8K8', first_name='Andrew', last_name='Brookins', email='andrew.brookins@example.com', join_date=datetime.date(2022, 1, 26), age=38, bio=None)]
```
Python 3.10.2
docker-compose version 1.29.2,
redis-om              0.0.17
module:name=ReJSON,ver=999999,api=1,filters=0,usedby=[search],using=[],options=[handle-io-errors]
module:name=search,ver=20206,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]

**Comment by gam-phon** [comment]
yes, it happens with me also, with redis database other than 0 no index are created

**Comment by BaronXOfficial** [comment]
I tried this solution, added db variable in the get_redis_connection args but it is still not working when attemping to .find() on the HashModel object searching for a particular entry.

**Comment by BaronXOfficial** [comment]
Changing db value in the above example works but in my particular case, where I am importing my DB model from another module, for whatever reason the same solution isn't working.

**Comment by BaronXOfficial** [comment]
Per my observations this issue is particularly prevalent when __name__ is not '__main__' - any ideas on how to work around this?

**Comment by simonprickett** [comment]
I'll take a look at this but note that using numbered databases in Redis isn't something we encourage.  It's usually better to use a key naming strategy that namespaces your keys in a single database.  Also note that if you run on Redis Enterprise/Cloud, there are no multiple databases, so commands such as `SELECT` won't work.

**Comment by simonprickett** [comment]
It appears that the index isn't getting created in database 1 and it doesn't show up in database 0 either... taking a look at this.

```bash
127.0.0.1:6379> ft._list
(empty array)
127.0.0.1:6379> select 1
OK
127.0.0.1:6379[1]> ft._list
(empty array)
```

**Comment by simonprickett** [comment]
@gam-phon @BaronXOfficial @Nishikoh I did some research and this doesn't work because index creation isn't supported on databases >0  in RediSearch.  I'll ask around but this is probably because Redis Enterprise doesn't use the `SELECT` command.

```
127.0.0.1:6379[1]> ft.create myindex on hash prefix 1 myhashes schema name text sortable
(error) Cannot create index on db != 0
```

I'd recommend using key namespaces rather than the `SELECT` command and different databases.

**Comment by simonprickett** [comment]
Added code to throw an exception if you attempt this https://github.com/redis/redis-om-python/pull/191
