### ISSUE TITLE
Can't define `model_key_prefix` in base class.

### ISSUE THREAD

**Issue by LeMoussel** [redis/redis-om-python#121]
Like describe in [The Meta Object Is "Special"](https://github.com/redis/redis-om-python/blob/main/docs/models.md#the-meta-object-is-special), It's not possible to define meta field `model_key_prefix` in base model.

```
class BaseModel(HashModel, ABC):
    class Meta:
        model_key_prefix= "some-information"

class Customer(BaseModel):
    first_name: str
    last_name: str
```

`Customer.model_key_prefix` value  is not set to "some-information" but, for example, `__main__.Customer`.

Indeed, I notice that in [model.py#L1059](https://github.com/redis/redis-om-python/blob/main/aredis_om/model/model.py#L1059), we have :
```
        if not getattr(new_class._meta, "model_key_prefix", None):
            # Don't look at the base class for this.
            new_class._meta.model_key_prefix = (
                f"{new_class.__module__}.{new_class.__name__}"
            )
```
It is then not possible to define `model_key_prefix` in base class.

Why is that?

**Comment by sav-norem** [comment]
It is possible - the syntax is just a bit obfuscated - this is what I have working 

`
class BaseModel(JsonModel):
    model_key_prefix = "some-information"

class Customer(BaseModel):
    first_name: str
    last_name: str

print(Customer.model_key_prefix.field)
`

`
name='model_key_prefix' type=str required=False default='some-information'`
