### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by h-attari** [redis/redis-om-python#126]
Cannot connect redis_om with django, was able to successfully connect redis-py with django using:
`redis.StrictRedis(host='127.0.0.1', port=6379, db=0)`
but when tried to connect the redis-om-model with django and fetched the existing data using:

`redis_om_conc = get_redis_connection(
    url="redis://127.0.0.1:6379/0",
    decode_responses=True
)

class GameList(HashModel):
    class Meta:
        database = redis_om_conc

    game_id: int
    game_name: str
    game_code: str
    display_platform: int
    vendor: str
    vendor_code: str
    vendor_id: int
    languages: str
    external_game_id: str

GameList.get("01FVF51D2K8WWTR2BTME97SWZ1")`

it throws an error as:

`NotFoundError                             Traceback (most recent call last)
Input In [12], in <module>
----> 1 GameList.get("01FVF51D2K8WWTR2BTME97SWZ1")

File ~/Projects/Feeder/cron-env/lib/python3.8/site-packages/redis_om/model/model.py:1324, in HashModel.get(cls, pk)
   1322 document = cls.db().hgetall(cls.make_primary_key(pk))
   1323 if not document:
-> 1324     raise NotFoundError
   1325 try:
   1326     result = cls.parse_obj(document)

NotFoundError:`

**Comment by vtiwarig** [comment]
Getting the Same Problem.

**Comment by wiseaidev** [comment]
I think, at the moment, it is not possible to use this package in django because django migrations and redis-om migrator are two different things, that's because `HashModel` is not a django model to apply migrations. So when you run:

```sh
python manage.py makemigrations
python manage.py migrate       
```

It will create an empty migration file. That's why you are getting:

```sh
    raise NotFoundError
aredis_om.model.model.NotFoundError
```
