### ISSUE TITLE
Importing redis_om can unexpectedly alter environment variables

### ISSUE THREAD

**Issue by aberres** [redis/redis-om-python#154]
In `redis_om/connections.py` we find a call to `dotenv.load_dotenv()` which is executed at import time. IMHO a library should never do such things - at least not silently. 

As an application developer, it is my responsibility ensure that all environment variables are read from whatever config I prefer. If I want to use dotenv to setup variables, it should be my job to do so.

**Comment by simonprickett** [comment]
First up sorry for the slow reply here... I took a look at this and user of dotenv seems to be minimal, and I'm pretty sure that it's just `REDIS_OM_URL`.  I think this would be safe to remove in a future release.

Usages of `dotenv`: https://github.com/redis/redis-om-python/search?q=dotenv

**Comment by simonprickett** [comment]
Fixed in 0.0.24 release.
