### ISSUE TITLE
error on fetch or filtering

### ISSUE THREAD

**Issue by alecvinent** [redis/redis-om-python#186]
Hello. I'm following the starter tutorial at https://www.youtube.com/watch?v=jJYHUp9ZeTY&t=56s.

I'm getting error when trying to fetch data from a HashModel. For example:
`result = Product.all_pks()`
gets: `redis.exceptions.ResponseError: syntax error`

For creating:
`exists = Product.find(Product.name == product.name).first()`
gets: `TypeError: 'NoneType' object is not subscriptable`

Creating is OK.

**Versions:**
Python version: 3.9.7
redis-om-python: 0.0.20

**Comment by simonprickett** [comment]
I'll take a look at this - this isn't one of our tutorial videos so I am not familiar with the content.

**Comment by alecvinent** [comment]
Hi. I've previously tried to enumerate the generator but without result.
Seen your answer, I've upgraded the redis-server from 5.0.7 to 6.2.6, but still failing.

Redis Server 6.2.6
Python 3.9.5 (downgraded from 3.9.7)
redis-om-python 0.0.20

```
from redis_om import Field

redis_instance = get_redis_connection(
    host=REDIS_HOST,
    port=REDIS_PORT,
    password='',
    db=REDIS_DB,
    decode_responses=True
)

class Product(HashModel):
    name: str = Field(index=True)
    price: float
    quantity: int

    class Meta:
        database: redis_instance

```

**Comment by simonprickett** [comment]
Is the value of `REDIS_DB` > 0?  RediSearch functionality only operates on DB 0 so if you're using search and the Migrator that will fail silently (I'm about to put out a release that will detect use of DB > 0 and raise a proper error).  This works locally for me:

```
$ python issue.py
['01G025DB81XWJ766JEHPYDV2HH']
```

```python
from redis_om import Field, HashModel, get_redis_connection

REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379
REDIS_DB = 0

redis_instance = get_redis_connection(
    host=REDIS_HOST,
    port=REDIS_PORT,
    password='',
    db=REDIS_DB,
    decode_responses=True
)

class Product(HashModel):
    name: str = Field(index=True)
    price: float
    quantity: int

    class Meta:
        database: redis_instance

a_product = Product(
    name="Test Product",
    price=10.99,
    quantity=4
)

a_product.save()

all_product_keys = list(Product.all_pks())
print(all_product_keys)
```

You could simplify this too as you don't need all the connection stuff:

```bash
$ export REDIS_OM_URL=redis://127.0.0.1:6379
$ python issue.py
['01G025GN8RQ1J0WRV5G96G0MM4']
```

You don't even need to set `REDIS_OM_URL` in this case as localhost, 6379, no password are the defaults.

Simplified code:

```python
from redis_om import Field, HashModel

class Product(HashModel):
    name: str = Field(index=True)
    price: float
    quantity: int

a_product = Product(
    name="Test Product",
    price=10.99,
    quantity=4
)

a_product.save()

all_product_keys = list(Product.all_pks())
print(all_product_keys)
```
