### ISSUE TITLE
Missing support for boolean field or examples of how to do it

### ISSUE THREAD

**Issue by sriveros95** [redis/redis-om-python#193]
I have a model  like
`
MyModel(HashModel):
    local_auth: bool
`
When initing or saving I get:
`DataError("Invalid input of type: 'bool'. Convert to a bytes, string, int or float first.")`

**Comment by simonprickett** [comment]
Hi there - boolean fields aren't yet supported for JSON or Hash, they'll likely appear in JSON first as boolean is a native type there vs a Redis Hash that understands strings, floats and ints.

**Comment by simonprickett** [comment]
I'm talking to the maintainers of the other Redis OM Clients for different languages to make sure that when we do add booleans to Python there's a common approach where possible.

**Comment by jrwagz** [comment]
@simonprickett , any update on native support for boolean fields?

**Comment by simonprickett** [comment]
@jrwagz I don't have an update here, copying in @dvora-h
