### ISSUE TITLE
Find by optional field returns documents with None

### ISSUE THREAD

**Issue by DennyD17** [redis/redis-om-python#247]
Hi!
I have model with Optional[int] indexed field and I want to query via that field. In results I see documents with None in that field. Why? How to avoid it? 

```
class Page(JsonModel):
    id: int = Field(index=True)
    base_id: Optional[int] = Field(index=True)

Migrator().run()
pages = Page.find(Page.base_id == 1).all()

``` 

In results I see docs with base_id = None

**Comment by sav-norem** [comment]
Thanks for bringing this up! Seems like right now the easiest way to get around this is to add a default value that would never exist in your data. I'll take a look through the source code and see what's going on!

**Comment by DennyD17** [comment]
Has it already been fixed? 
Can't reproduce it 

redis-om = "^0.1.2"
