### ISSUE TITLE
Document toml file for FastAPI integraion

### ISSUE THREAD

**Issue by anivle** [redis/redis-om-python#29]
[FastAPI integraion documentation](https://github.com/redis/redis-om-python/blob/main/docs/fastapi_integration.md) says project could be used as is. But there is no `toml` file for this Poetry project.
I've created one via `poetry init` but there still need to be `test` attribute in `main` module. Without it, following command is not working properly
```
$ poetry run uvicorn --reload main:test
```
Getting following error on launch:
```
ERROR:    Error loading ASGI app. Attribute "test" not found in module "main".
```

**Comment by abrookins** [comment]
Thanks @anivle! You're totally right. I needed to tidy up that document, and also link to the example app repo that has a pyproject.toml file. This should be fixed now.
