### ISSUE TITLE
Index embedded models

### ISSUE THREAD

**Issue by erniavr** [redis/redis-om-python#351]
Please add the ability to mark class members of EmbeddedJsonModel as indexed when the EmbeddedJsonModel is in a List in the JsonModel.

**Comment by sav-norem** [comment]
@simonprickett 

I believe this is already implemented - [here's](https://github.com/redislabs-training/ru204/blob/f404223d775854a1a91b0d25781a137b8b8a2b25/src/python/redis_om_search_example/model.py#L11) an example with a list of EmbeddedJsonModel and the embedded model has members indexed.
