### ISSUE TITLE
Migrator using get_redis_connection

### ISSUE THREAD

**Issue by th3happybit** [redis/redis-om-python#45]
Hello, I'm trying to use `Migrator` with `get_redis_connection` like in the docs: https://redis.com/blog/introducing-redis-om-for-python/ but I'm facing this error, please help if you have an idea about it

```
In [11]: from redis_om import get_redis_connection

In [12]: get_redis_connection()
Out[12]: Redis<ConnectionPool<Connection<host=localhost,port=6379,db=0>>>

In [13]: Migrator(get_redis_connection()).run()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-00d45abb5072> in <module>
----> 1 Migrator(get_redis_connection()).run()

~/dev/redis-om-python-search-demo/venv/lib/python3.9/site-packages/redis_om/model/migrations/migrator.py in run(self)
    154         # TODO: Migration history
    155         # TODO: Dry run with output
--> 156         self.detect_migrations()
    157         for migration in self.migrations:
    158             migration.run()

~/dev/redis-om-python-search-demo/venv/lib/python3.9/site-packages/redis_om/model/migrations/migrator.py in detect_migrations(self)
     92         # Try to load any modules found under the given path or module name.
     93         if self.module:
---> 94             import_submodules(self.module)
     95 
     96         # Import this at run-time to avoid triggering import-time side effects,

~/dev/redis-om-python-search-demo/venv/lib/python3.9/site-packages/redis_om/model/migrations/migrator.py in import_submodules(root_module_name)
     22     """Import all submodules of a module, recursively."""
     23     # TODO: Call this without specifying a module name, to import everything?
---> 24     root_module = importlib.import_module(root_module_name)
     25 
     26     if not hasattr(root_module, "__path__"):

/usr/lib/python3.9/importlib/__init__.py in import_module(name, package)
    116     """
    117     level = 0
--> 118     if name.startswith('.'):
    119         if not package:
    120             msg = ("the 'package' argument is required to perform a relative "

AttributeError: 'Redis' object has no attribute 'startswith'
```

also how I can set the host of redis without using `get_redis_connection` if that possible

**Comment by th3happybit** [comment]
solved by using the `REDIS_OM_URL` environment variable [as mentioned here ](https://github.com/redis/redis-om-python/blob/main/docs/connections.md)

using it with docker and docker-compose: [forked demo](https://github.com/th3happybit/redis-om-python-search-demo)

**Comment by abrookins** [comment]
@th3happybit Did setting `REDIS_OM_URL` also help with the migrations error?

**Comment by th3happybit** [comment]
> @th3happybit Did setting `REDIS_OM_URL` also help with the migrations error?

No, the error is still there if we pass the `redis` connection object to `Migrator()`

**Comment by gam-phon** [comment]
Check this commit: https://github.com/redis/redis-om-python/commit/269d44c26e4cc3c2fb35cc1053dd85d5633bc1a2#diff-279e18c65ed8a0504721b3eb6a9aaa38e4947d209799c5ae6aecf066fc9b6343

you should not pass redis to Migrator. before it works but with the latest you should not do it. It will take redis client from each moudle itself

**Comment by simonprickett** [comment]
@th3happybit Hi there - I don't think there'a any further action needed here, so I'll close this issue if you agree.

**Comment by th3happybit** [comment]
> @th3happybit Hi there - I don't think there'a any further action needed here, so I'll close this issue if you agree.

Yeah sure you can close it, thank you

**Comment by simonprickett** [comment]
Closing.
