### ISSUE TITLE
[Enhancement] Support Pydantic v2

### ISSUE THREAD

**Issue by XChikuX** [redis/redis-om-python#525]
![image](https://github.com/redis/redis-om-python/assets/5894493/07352fff-3374-4144-bc15-d403e66a78bb)

Pydantic v2 comes with several performance and safety benefits due to being compiled in Rust with python bindings.

I'd love to see the models: HashModel, JsonModel, EmbeddedJsonModel all use the new and improved pydantic.

There maybe a small migration workflow, which the pydantic team is building a tool for.

**Comment by bonastreyair** [comment]
take a look at https://docs.pydantic.dev/latest/migration/
also take a look at this tool that will automatically upgrade some of the changes for you: https://github.com/pydantic/bump-pydantic

**Comment by XChikuX** [comment]
So far, commit #533 does not successfully support Pydantic v2. Keeping this open.

**Comment by pr0ton11** [comment]
Also waiting for this to be supported.
