### ISSUE TITLE
Person.find(person.pk == id).first() returns empty even if there is an object

### ISSUE THREAD

**Issue by Sreesanth46** [redis/redis-om-python#575]
I got this issue when updating a Model and then finding the same model that I updated. 

this is my code
`def get_campaign_by_id_and_client_id(id, client_id):
    try:
        return InterviewRedisModel.find(
            InterviewRedisModel.pk == id,
            InterviewRedisModel.created_by == client_id
        ).first()
    except NotFoundError:
        raise CampaignNotFoundException("Campaign not found")`
        
 First time it returns the object as expected. Next time it raises the exception.
 But when I do a get() query instead
 `InterviewRedisModel.get(pk = id)`
 This returns even if the find returns empty/NotFoundError

**Comment by dearkafka** [comment]
check types, for me it was the problem @Sreesanth46 . If you do update or anything like that and alter types your item becomes unsearchable

**Comment by Sreesanth46** [comment]
@dearkafka issue was with the number of indexed fields. Solved the issue by reducing the number of indexed fields.

There is still no document specifying the maximum number of indexed fields that we can use in a document.

**Comment by dearkafka** [comment]
Mamma Mia!

**Comment by slorello89** [comment]
The limit is 1024. If you are using lots of text fields, that changes things somewhat (I think the limit is lower -like 128 or something)

**Comment by slorello89** [comment]
Going to close this as it's resolved.
