### ISSUE TITLE
Does Redis-om support fuzzy search

### ISSUE THREAD

**Issue by saifullah-repliq** [redis/redis-om-python#578]

**Comment by slorello89** [comment]
Yes, you fuzzy matching can be done by surrounding the word you are interested in with `%`, that will do a match up to a levenshtein distance of the number of `%` on either side of the search term:

```py
Member.find(m.Member.bio % "%parey%") # levenshtein of 1
Member.find(m.Member.bio % "%%parey%%") # levenshtein of 2
Member.find(m.Member.bio % "%%%parey%%%") # levenshtein of 3
```

this will work up to a levenshtein of 3

See [Fuzzy Searching](https://redis.io/docs/latest/develop/interact/search-and-query/query/full-text/#fuzzy-search) in our docs for more details.
