### ISSUE TITLE
can we have A null/None expression in the find

### ISSUE THREAD

**Issue by muslih-DIY** [redis/redis-om-python#582]
can we have a null expression like 

```python
AgentDevice.find(None).all()

AgentDevice.find(
(AgentDevice.device== 1) & (AgentDevice.center== center if center else None )
 ).all()

**Comment by muslih-DIY** [comment]
from redis_om.model.model import Expression, Operators
ALL_EXPRESSION = Expression(op=Operators.ALL, left=None, right=None, parents=[])
AgentDevice.find(ALL_EXPRESSION).all()

This one is working

**Comment by slorello89** [comment]
None / null types are not searchable in Redis, so we can't really support this at the moment. going to close this out to tidy up.
