### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by vbabiy** [redis/redis-om-python#596]
Seeking clarification on the current status of the redis-om-python project. Is this project still actively maintained, or can it be considered a dead project?

There hasn't been a release in a while.

**Comment by gaby** [comment]
I had the same question, there's a lot of pending PR's that need to be merged.

This library is mentioned in the docs for Redis Stack but hasnt been updated in a while

**Comment by gaby** [comment]
Ping @chayim @dvora-h @moznuy

**Comment by banker** [comment]
We apologize for the delay in responding to these issues, and we're working on a plan here at Redis to get a more permanent maintainer on board. I don't have a timeline on this just yet, but we'll respond with an update within the next couple of weeks.

**Comment by gaby** [comment]
@banker If it helps I can make a PR that consolidate the critical PR's that are pending.

The biggest issue right now is the update for Pydantic, and few chores stuff with GitHub Actions. Also adding py3.12 to the CI.

**Comment by banker** [comment]
@gaby If you can make a PR that consolidates the highest priority issues, we'd very much appreciated it. Thanks in advance!

**Comment by gaby** [comment]
Small update, I have over +30 commits in my fork. Some notes:

- codecov now requires a token to upload coverage reports
- mypy fails to run if pydantic is higher than 2.5.x or higher.
- When using latest pydantic/mypy there's over 100 errors.

Besides the issues above all the tests pass, including py3.12 and pypy-3.10

**Comment by gaby** [comment]
@banker PR has been submitted.

**Comment by banker** [comment]
Got it. Thanks, @gaby. We'll take a look.

**Comment by banker** [comment]
Oh, and thanks very much for putting together this PR, @gaby! I think we should be able to merge this into a new release fairly quickly.

**Comment by gaby** [comment]
Awesome, thank you! 💪

**Comment by gaby** [comment]
> Pushed a new release based on @gaby's PR. Thanks so much! We'll plan to stay more on top of this from here on out.

Awesome! Thank you so much! 💪 Looking forward!
