### ISSUE TITLE
Does redis-om support redlock?

### ISSUE THREAD

**Issue by koujiangheng** [redis/redis-om-python#598]
If the multiple micro-services should modify single object on redis, whether redis-orm python can provide redlock to ensure only one is modifying that object?

**Comment by slorello89** [comment]
There any redlock integration with Redis OM Python. But updates do occur in isolation (they are HSET/JSON.SET), so there won't be a case where two clients are updating the same object at exactly the same time, and you can always wrap your updates with redlock if needed.

**Comment by slorello89** [comment]
closing to tidy up
