### ISSUE TITLE
JsonModel.schema_for_type() missing 2 required positional arguments: 'typ' and 'field_info'

### ISSUE THREAD

**Issue by DennyD17** [redis/redis-om-python#619]
redis-om = "^0.3.1"

Here we try to pass 3 args to schema_for_type
https://github.com/redis/redis-om-python/blob/main/aredis_om/model/model.py#L1985

But it seems like it takes 5 
https://github.com/redis/redis-om-python/blob/main/aredis_om/model/model.py#L1994

So I get 
JsonModel.schema_for_type() missing 2 required positional arguments: 'typ' and 'field_info'

**Comment by slorello89** [comment]
Hi @DennyD17 - I really need a reproduction of this issue to make any progress.

**Comment by DennyD17** [comment]
```
            if getattr(field_info, "primary_key", None):
                if issubclass(_type, str):
                    redisearch_field = f"$.{name} AS {name} TAG SEPARATOR {SINGLE_VALUE_TAG_FIELD_SEPARATOR}"
                else:
                    redisearch_field = cls.schema_for_type(name, _type, field_info)
                schema_parts.append(redisearch_field)
                continue
```

If we create JsonModel with non-str pk we will get this error

```
class MyModel(JsonModel):
    my_id: int = Field(index=True, primary_key=True)
```

Here you pass 3 positional arguments to method expecting 5 

`redisearch_field = cls.schema_for_type(name, _type, field_info)`
