### ISSUE TITLE
Insecure setuptools

### ISSUE THREAD

**Issue by markedwards** [redis/redis-om-python#643]
`redis-om` depends on `setuptools` <70.0.0 which has a high severity security vulnerability:

https://github.com/advisories/GHSA-cx63-2mw6-8hw5

This is preventing projects using `redis-om` from patching the vulnerability.  Can this be remedied asap?

**Comment by jayes33** [comment]
+ need this remediated as soon as possible

**Comment by slorello89** [comment]
fixed in 0.3.2.
