### ISSUE TITLE
redis.exceptions.ResponseError: unknown command 'module'

### ISSUE THREAD

**Issue by alex-ge123** [redis/redis-om-python#659]
https://github.com/user-attachments/assets/e18dea49-f116-438d-901b-e3f3bfe7fe4d

**Comment by slorello89** [comment]
The `MODULE` command is used by redis OM python to ensure you have the correct modules installed to proceed with usage. My guess is you don't have a valid version of Redis running with the MODULE command (probably an older version of Redis as the MODULE command was introduced in version 4.0)
