### ISSUE TITLE
Wildcard searching in redis-om-python ? 

### ISSUE THREAD

**Issue by therealbazzi** [redis/redis-om-python#77]
Hi,

Can we perform (like in rediSearch) wildcard (asterisk) searching in redis-om in python ? 

For this [video](https://youtu.be/DFNKmbGKa5w) - i tried for example:

`Adoptable.find(Adoptable.name == 'A*').all()
`
but it does not do the job

**Comment by simonprickett** [comment]
I don't expect that to work as wildcard searching in RediSearch just returns all items... see the [Query Syntax documentation for RediSearch](https://oss.redis.com/redisearch/Query_Syntax/).

> A special "wildcard query" that returns all results in the index - * (cannot be combined with anything else).
