### ISSUE TITLE
Document how to get to the underlying lower level Redis client and run both normal and module commands.

### ISSUE THREAD

**Issue by simonprickett** [redis/redis-om-python#81]
Document how to access the underying low level Redis client, in order to run commands it understands e.g. `GET`, `SET` plus those it doesn't which will mosty relate to modules e.g. `BF.ADD`.

**Comment by simonprickett** [comment]
Example of how to do this for reference:

```python
from redis_om import get_redis_connection

redis_conn = get_redis_connection()
redis_conn.set("hello", "world")
```

**Comment by gam-phon** [comment]
Also this

```python
class Customer(JsonModel):
    name: str

redis_conn = Customer.db()
redis_conn.set("hello", "world")
```

**Comment by simonprickett** [comment]
This also needs documenting for use in async code.

**Comment by simonprickett** [comment]
When documenting this, use `expire` as the example.
